### PR TITLE
fix height IDE preview bug

### PR DESCRIPTION
**Pull request by manuIO**

### CODE REVIEW

**Comment by drasko** [comment]
@nmarcetic can you please review this before merge, please.

**Comment by manuIO** [comment]
@nmarcetic I've only changed this line: https://github.com/manuIO/weio/commit/339875062ed6c0d3d9c40722e0133a0fab4aa007#diff-b62ecd8d7fee6978acb0ddda272544f9R436

The others modification are onely some clean-up.

I've tried some methods to set "height" of "iframeContainerIndex" at 100% like in "iframeContainer" but it doesn't work... Maybe you know better solution ?

**Comment by nmarcetic** [comment]
@manuIO  With current structure this is  less painful approach. 
Thanks!

**Comment by manuIO** [comment]
@nmarcetic Cool! 
@drasko If is good for everyone this issue can be closed: https://github.com/nodesign/weio/issues/43

**Pull request merged**
