### PR TITLE
rm useless potar function

### PR DESCRIPTION
**Pull request by DervanM**
Potar() function does nothing in particular and calls the function sleeps, this makes the application slower, without it the color changes with more synchrony

### CODE REVIEW

**Comment by drasko** [comment]
@DervanM what do you mean by this "does nothing in particular"? From what I see this function reads a potentiometer attached to pin 25 (you have to attach it manually to your board) and based on it's analog value sets the color value, then pushes this data towards browser client (https://github.com/DervanM/weio/blob/next/examples/webApps/bgColorLEDWEB/main.py#L51).

Btw, sleeping of a `potar()` process does not make the program slower - every WeIO process is launched as a separate Python thread, and they work all in parallel. So, while one thread is sleeping, other things in the program are happening as usual.

**Comment by DervanM** [comment]
you are right, its reads a potentiometer attached on pin 25, but why do you
want pushes the values of potentiometer if you also changes the values with
the gyroscope of the smartphone. because this example for me shows us, how
can we use the gyro for change the color of background of the http page.

when i tested this, with the potar function, the local page, are green
default color, i use the gyro and that change the color to another one,
good, but then green is back cause the potar function.


2016-03-21 17:35 GMT+01:00 Drasko DRASKOVIC <notifications@github.com>:

**Comment by drasko** [comment]
I think that this example was made to demonstrate both client-to-server (data from phone gyro, in the form of `event`) and server-to-client communication (data from analog input).

I agree that this can be confusing and one can affect other in unpredictable manner.

@ukicar @ks156 @manuIO - any opinions on this?

**Comment by manuIO** [comment]
I'm also agree that this example can be confusing. 
Maybe it could be better if this example is divided into two different ones. 

BTW the name of the example is not really understandable and it's a pity because this example is really cool!

**Comment by drasko** [comment]
+1 for 2 separated examples.

@DervanM would you like to do the separation of the example in 2 different examples with logical names (I agree with @manuIO that name of the example is confusing)?

If yes, I would gladly accept PR

**Comment by DervanM** [comment]
yes i would like to do the separation,

ok, separate in 2 examples is not a good idea because weio becomes less
powerful than it's build for, so I'll try to do as:

1 : gyroPhoneToEvent(); client-to-server

data from phone gyro, in the form of event, the local page opened in a mac
changes it's background color from data gyros of phone.

2 : dataFromAnalogInput(), use case
server-to-client communication (data from analog input). that
demonstrate both client-to-server,


server-to-client communication (data from analog input).




2016-03-21 21:30 GMT+01:00 Drasko DRASKOVIC <notifications@github.com>:

**Comment by DervanM** [comment]
excuse me, my missclick, i wasnt finished

2016-03-22 13:49 GMT+01:00 Dervan Montecinos <dervanm@gmail.com>:

**Comment by drasko** [comment]
@DervanM  great! This idea looks good to me.

I will the close this PR, and will be waiting to next two PRs from you that replace this PR.

**Pull request closed without merging**
