### PR TITLE
add run without main.py support & fix print of long strings in IDE console 

### PR DESCRIPTION
**Pull request by manuIO**

### CODE REVIEW

**Comment by drasko** [comment]
This touches system. We must re-test before merge (I prefer not to merge this one automatically)
@ukicar test this also on your side, please.

**Comment by drasko** [comment]
Why are you checking here: https://github.com/manuIO/weio/blob/next/weioPlayer.py#L133 if default main.py exists, when you know it exits?

Everything else looks good to me (but I have to test on the board).

**Comment by manuIO** [comment]
Yes right, is not really useful... I forgot to remove this "if".
Let me change that!

**Comment by drasko** [comment]
Please do and re-check everything on the board, with various scenarios. This is very sensitive part you are changing. @ukicar has to re-check also, and he will do this over the WE.

Changes looks OK, but you are touching a core system, and I am very afraid not to break something.

**Comment by manuIO** [comment]
I've tested with several examples and various scenarios and it works good for me! 
I hope that @ukicar will get the same result!

I've noticed strange behaviors running i2c example. I get same strange behavior without lasts commits, so I think that is a real bug with I2C bus: https://github.com/nodesign/weio/issues/145

**Comment by manuIO** [comment]
can be closed?

**Comment by manuIO** [comment]
I've done manually new PR to prevent conflict: https://github.com/nodesign/weio/pull/181
Can be closed!

**Pull request merged**
