### PR TITLE
Clean and minimal config for Chaos Calmer

### PR DESCRIPTION
**Pull request by ks156**

### CODE REVIEW

**Comment by drasko** [comment]
Please revise Bysybox config. I can see `CONFIG_BUSYBOX_DEFAULT_FEATURE_IPV6` activated. Might be some other unnecessary stuff.

**Comment by ks156** [comment]
I didn't check busybox. I though you did it in your minimal config. I'll check it now

**Comment by drasko** [comment]
Hmmm... I though I did also :).

Try to correct as much as you can, I will launch the build after your commit.

**Comment by drasko** [comment]
In fact, maybe this can wait tomorrow, so I can pick up `pip` changes, if you will have any. I see no more corrections after this `.config` and `pip`, I would ACK v1.2 tagging.

**Comment by ks156** [comment]
What's the problem with pip ?

**Comment by drasko** [comment]
I'll currently merge this, so we have something right away for testing. Re-post new PR when you correct the changes.

**Comment by ks156** [comment]
> I can see CONFIG_BUSYBOX_DEFAULT_FEATURE_IPV6 activated

I can't find how to deactivate it. I don't see it in the menu, and even manually in .config, it's reactivated via menuconfig ...

**Comment by drasko** [comment]
@ks156 `pip` related stuff commented here: https://github.com/nodesign/weio/issues/132. We can have new `pip` from CC feeds installed during image build. No need for additional `opkg install`s.

**Pull request merged**
